# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9356f4dd74c404e5edefc3ae16a24f5de6c7ea2e7e60df5dc10a6b25f040cc1c9b33f02eb8158aa72507afa0545822b453a81ea6a2cc0e4abfc4130b16b091d3

test:
  secret_key_base: 10a277fd63cc25da8e16a04dfa4bc878e839858c756690ecd887a7d85addaef85dc8283ed9d5137a215aed3d156b857ea3033e8d56ae08087fc1aa3b86874f29

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
